"""ports：core 對持久層的**全部**要求，以 Protocol 寫下；SQL 實作在 `rtgaia_server.adapters`。

原則：介面直接從既有實作的**已被呼叫的方法**抽出，不預測；不夠再加（加介面比改介面便宜）。
core 不 import `rtgaia_server`／`rtgaia_testbe`（`tests/test_layering.py` 斷言）。
記憶體實作（`MemoryJobQueue`、`LocalBus`、`MemoryNodes`…）在 core 自己這裡，所以沒有 DB 時不需要任何 adapter。
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any, Protocol


class CatalogRepository(Protocol):
    """`CatalogStore`：目錄（patient／study／series）持久層；`engine` 給其他 store 共用。"""

    engine: Any

    async def ping(self) -> bool: ...
    async def counts(self) -> dict[str, int]: ...
    async def dispose(self) -> None: ...
    async def load_index(self, root: Any) -> Any: ...
    async def previous_map(self) -> dict[str, Any]: ...
    async def replace_headers(self, root: Any, headers: list[Any]) -> Any: ...
    async def generation(self) -> int: ...


class CaseRepository(Protocol):
    """`CaseStore`：病例／結構／版本／簽核／量測的持久層（`api/deps.py` 用到的那幾個）。"""

    async def persist(self, case: Any, *, created_by: str = "") -> dict[str, int]: ...
    async def load(self, case_id: str) -> Any: ...
    async def list(self) -> list[dict[str, Any]]: ...
    async def find_by_selection(self, selection_hash: str) -> str | None: ...
    async def adopt_work_sets(self, new_case_id: str, frame_of_reference_uids: list[str]) -> list[dict[str, Any]]: ...
    async def worklist_rows(self) -> list[dict[str, Any]]: ...


class AuditRepository(Protocol):
    async def append(self, event: dict[str, Any]) -> None: ...


class UserRepository(Protocol):
    async def get(self, username: str) -> Any: ...


class NodeRepository(Protocol):
    async def list(self) -> list[Any]: ...
    async def get(self, node_id: str) -> Any: ...
    async def put(self, node: Any) -> Any: ...
    async def delete(self, node_id: str) -> None: ...


class SettingsRepository(Protocol):
    async def get(self, key: str) -> dict[str, Any] | None: ...
    async def meta(self, key: str) -> dict[str, Any] | None: ...
    async def put(self, key: str, value: dict[str, Any], *, updated_by: str) -> None: ...


class PluginRepository(Protocol):
    async def list(self) -> list[Any]: ...
    async def get(self, plugin_id: str) -> Any: ...
    async def put(self, rec: Any) -> Any: ...
    async def delete(self, plugin_id: str) -> None: ...


class ExportRecordRepository(Protocol):
    """`export_record`。記憶體實作 `rtgaia_core.export_records.MemoryExportRecords`。"""

    async def put(self, rec: Any) -> Any: ...
    async def get(self, export_id: str) -> Any: ...
    async def list(
        self,
        *,
        case_id: str | None = None,
        patient_id: str | None = None,
        requested_by: str | None = None,
        kind: str | None = None,
        status: str | None = None,
        limit: int = 100,
    ) -> list[Any]: ...


Deliver = Callable[[str, str, dict[str, Any]], Awaitable[int]]


class Adapters(Protocol):
    """有 DB 時由誰把 SQL 實作接進 `AppState`。`rtgaia_server.adapters.SqlAdapters` 是唯一實作；
    沒有 DB（純記憶體、e2e 假體）時 `AppState.adapters` 可以是 None。"""

    def catalog_store(self, db_url: str) -> CatalogRepository: ...
    def upgrade_to_head(self, db_url: str) -> None: ...
    def case_store(self, engine: Any, blobs: Any) -> CaseRepository: ...
    def rebuild_structures(self, loaded: Any, store: CaseRepository) -> dict[tuple[str, int | None], Any]: ...
    def audit_store(self, engine: Any) -> AuditRepository: ...
    def user_store(self, engine: Any) -> UserRepository: ...
    def nodes(self, engine: Any) -> NodeRepository: ...
    def settings(self, engine: Any) -> SettingsRepository: ...
    def plugins(self, engine: Any) -> PluginRepository: ...
    def job_queue(self, engine: Any) -> Any: ...
    def export_records(self, engine: Any) -> ExportRecordRepository: ...
    def storage_locations(self, engine: Any) -> Any: ...
    def bus(self, engine: Any, db_url: str, deliver: Deliver | None) -> Any: ...


class NoAdapters(RuntimeError):
    """設了 `RTGAIA_DB_URL` 但 app 沒有帶 SQL adapters
    （例如直接用 `rtgaia_core.api.create_app` 而不是 `rtgaia_server.app.create_app`）。"""
